import { setCompodocJson } from '@storybook/addon-docs/angular';
import docJson from '../documentation.json';
setCompodocJson(docJson);

const customViewports = {
  smallDevice: {
    name: 'Small device',
    styles: {
      width: '375px',
      height: '812px',
    },
    type: 'mobile',
  },
  largeDevice: {
    name: 'Large device',
    styles: {
      width: '576px',
      height: '812px',
    },
    type: 'mobile',
  },
  tablet: {
    name: 'Tablet',
    styles: {
      width: '768px',
      height: '1024px',
    },
    type: 'tablet',
  },
  smallDesktop: {
    name: 'Small desktop',
    styles: {
      width: '1024px',
      height: '720px',
    },
    type: 'desktop',
  },
  largeDesktop: {
    name: 'Large desktop',
    styles: {
      width: '1440px',
      height: '1024px',
    },
    type: 'desktop',
  },
};

export const parameters = {
  actions: { argTypesRegex: '^on[A-Z].*' },
  controls: {
    expanded: true,
    matchers: {
      color: /(background|color)$/i,
      date: /Date$/,
    },
  },
  docs: { inlineStories: true },
  options: {
    storySort: {
      order: [
        'Introduction',
        'Color Scale',
        'Theming',
        'Iconography',
        'Typography',
        'Scrollbar',
        'Components',
        [
          'Alert Banner',
          ['Basic Usage'],
          'Bottom Sheet',
          ['Basic Usage'],
          'Breadcrumbs',
          ['Basic Usage'],
          'Buttons',
          [
            'Primary Button',
            'Secondary Button',
            'Text Button',
            'Labeled Icon Button',
            'Primary Icon Button',
            'Secondary Icon Button',
            'Text Icon Button',
            'Toggle Button',
          ],
          'Chip',
          'Checkbox',
          ['Basic Usage', 'Alignment', 'Hierarchy', 'Forms integration'],
          'Currency',
          ['Basic Usage'],
          'Datepicker',
          ['Basic Usage'],
          'Dropdown',
          ['Basic Usage'],
          'File Uploader',
          ['Drag and drop', 'File Display'],
          'File Viewer',
          'Filter Bar',
          ['Basic Usage'],
          'Filter Chip',
          ['Boolean Filter Chip'],
          'Flyout Menu',
          ['Basic Usage'],
          'Form Field',
          ['Helper Text', 'Error Text'],
          'Hyperlink',
          'Input',
          ['Basic usage', 'Forms integration', 'Password Strength'],
          'Kabob',
          'List Item',
          ['Checkbox List Item', 'Radio List Item', 'Menu List Item'],
          'Loading Spinner',
          'Menu Button',
          ['Single option', 'Multiple option'],
          'Messaging Card',
          ['Basic Usage'],
          'Modal',
          ['Basic Usage'],
          'Note Card',
          ['Basic Usage'],
          'Notification Badge',
          ['Basic Usage'],
          'Panel',
          'Product Tile',
          'Progress Bar',
          ['Determinate'],
          'Radio button',
          ['Basic Usage'],
          'Search Input',
          ['Basic Usage'],
          'Selector Cards',
          ['Chevron', 'Checkbox'],
          'Suggested Action Module',
          ['Basic Usage'],
          'Slider',
          'Table',
          [
            'Basic usage',
            'Column resize', 
            'Header Flyout', 
            'Inline actions' ,
            'Scrolling' 
          ],
          'Tabs',
          ['Basic usage'],
          'Timer',
          ['Basic usage'],
          'Toast',
          ['Basic usage'],
          'Tooltip',
          ['Basic usage'],
          'Top Bar',
          ['Brand Top Bar', 'Contextual Top Bar', 'Progress Bar'],
        ],
      ],
    },
  },
  viewport: {
    viewports: customViewports,
  },
};
