export enum Uk2Tier1InvestEnum {
  wallet = 'uk2-wallet',
  priceTag = 'uk2-price-tag',
  percentCircle = 'uk2-percent-circle',
  coinHand = 'uk2-coin-hand',
  merge = 'uk2-merge',
  split = 'uk2-split',
  nestEgg = 'uk2-nest-egg',
  moneyJar = 'uk2-money-jar',
  education = 'uk2-education',
  etf = 'uk2-etf',
  shortSell = 'uk2-short-sell',
  trading = 'uk2-trading',
  moneyBag = 'uk2-money-bag',
  options = 'uk2-options',
  moneyStack = 'uk2-money-stack',
  bagHand = 'uk2-bag-hand',
  shortInterest = 'uk2-short-interest',
}
