export enum Uk2Tier1FilesEnum {
  fileBlank = 'uk2-file-blank',
  file = 'uk2-file',
  filePlus = 'uk2-file-plus',
  filePdf = 'uk2-file-pdf',
  fileRibbon = 'uk2-file-ribbon',
  clipboard = 'uk2-clipboard',
  clipboardCheck = 'uk2-clipboard-check',
  scroll = 'uk2-scroll',
  picture = 'uk2-picture',
  presentation = 'uk2-presentation',
  pencilWritingFill = 'uk2-pencil-writing-fill',
  pencil = 'uk2-pencil',
  pencilWriting = 'uk2-pencil-writing',
  disk = 'uk2-disk',
  printer = 'uk2-printer',
  link = 'uk2-link',
  cdMaturity = 'uk2-cd-maturity',
  internet = 'uk2-internet',
  pencilFill = 'uk2-pencil-fill',
}
