export enum Uk2Tier1NavigationEnum {
  arrowBack = 'uk2-arrow-back',
  arrowForward = 'uk2-arrow-forward',
  arrowBackCurve = 'uk2-arrow-back-curve',
  chevronLeft = 'uk2-chevron-left',
  chevronRight = 'uk2-chevron-right',
  chevronDown = 'uk2-chevron-down',
  chevronUp = 'uk2-chevron-up',
  arrowsHorizontal = 'uk2-arrows-horizontal',
  arrowsVertical = 'uk2-arrows-vertical',
  arrowsCircular = 'uk2-arrows-circular',
  x = 'uk2-x',
  hamburger = 'uk2-hamburger',
  ellipsesHorizontal = 'uk2-ellipses-horizontal',
  ellipsesVertical = 'uk2-ellipses-vertical',
  logInR = 'uk2-log-in-R',
  logInL = 'uk2-log-in-L',
  logOutR = 'uk2-log-out-R',
  logOutL = 'uk2-log-out-L',
  doubleChevronsRight = 'uk2-double-chevrons-right',
  doubleChevronsLeft = 'uk2-double-chevrons-left',
}
